apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  DATABASE_URL: "postgresql://mamba:mamba123@host.docker.internal:5436/mydb?sslmode=disable"