apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

images:
  - name: mambak10099/devops-app
    newTag: latest

patches:
  - path: replica-count.yaml
    target:
      kind: Deployment
  - path: env-dev.yaml
    target:
      kind: ConfigMap